# Generated by Django 4.1.2 on 2022-10-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=10)),
                ('start', models.CharField(max_length=250)),
                ('finish', models.CharField(max_length=250)),
                ('identifiers', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_CATEGORY', models.CharField(max_length=150)),
                ('customer', models.CharField(max_length=150)),
                ('identifier', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Awaiting confirmation', 'Awaiting confirmation'), ('Dispaching Help', 'Dispaching Help'), ('Responded', 'Responded'), ('Cancelled', 'Cancelled')], default='Awaiting confirmation', max_length=250)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
    ]
