# Generated by Django 4.1.2 on 2022-10-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporting',
            old_name='SERVICE_CATEGORY',
            new_name='SERVICECATEGORY',
        ),
        migrations.AddField(
            model_name='service',
            name='SERVICE_CATEGORY',
            field=models.CharField(choices=[('RA', 'RA'), ('FI', 'FI'), ('RC', 'RC'), ('ME', 'ME'), ('SA', 'SA'), ('DV', 'DV'), ('SUA', 'SUA')], default='Awaiting confirmation', max_length=250),
        ),
    ]
