# Generated by Django 4.1.2 on 2022-10-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_service_category_reporting_servicecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
    ]
