# Generated by Django 4.1.2 on 2022-10-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Hospital', 'Hospital'), ('Police', 'Police'), ('Ambulance', 'Ambulance'), ('Fire Station', 'Fire Station'), ('Tow Service', 'Tow Service'), ('Gender service', 'Gender service'), ('Couselling Center', 'Couselling Center')], max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('descriprition', models.CharField(max_length=400)),
                ('contact', models.CharField(max_length=150)),
            ],
        ),
    ]
