# Generated by Django 4.1.7 on 2023-02-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_responder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='SERVICE_CATEGORY',
            field=models.CharField(choices=[('RA', 'RA'), ('FI', 'FI'), ('RC', 'RC'), ('ME', 'ME'), ('GBV', 'GBV'), ('CR', 'CR'), ('SUD', 'SUD')], default='Awaiting confirmation', max_length=250),
        ),
    ]
